#spring.application.name=Oauth2-authorization-server

#  ,client_secret_post,client_secret_jwt

spring:
  application:
    name: Oauth2-authorization-server
#    spring:
#      security:
#        oauth2:
#          authorization server:
#            client:
#              client-1:
#                #require-authorization-consent: true
#                registration:
#                  client-id: "client"
#                  # the client secret is "secret" (without quotes)
#                  client-secret: "{bcrypt}$2a$12$4U3GR70Y.rAumsMxoxU.3.DL2r/82her/UEfVM2weGQ0mbg08s79C"
#                  client-authentication-methods: "client_secret_basic"
#                  authorization-grant-types: "client_credentials"
#                  redirect-uris: http://localhost:8082/login/oauth2/code/spring
#                  scopes: "openid"
#                token:
#                  access-token-time-to-live: 30s